name: Functions
version: '3.0.0.0'
main: org.functions.Bukkit.Main.Functions
softdepend: [ Vault, PlaceholderAPI ]
authors: [ 2b2ttianxiu ]
description: Hello
website: 2b2ttanxiu.github.io
commands:
  functions:
    description: Functions main commands.
    aliases: [fun]
  help:
    description: Functions help player.
  group:
    description: Functions group player.
  back:
    description: Functions back player last death.
  home:
    description: Functions home player.
  report:
    description: Functions report hacker.
  suicide:
    description: Functions suicide player.
  permission:
    description: Functions set permission in the group or user permission.
  op:
    description: Functions give player operator.
  deop:
    description: Functions delete player operator.
  warps:
    description: Functions warp player.
  economy:
    description: Functions economy.
  money:
    description: Functions money.
  pay:
    description: Functions pay.
  hat:
    description: Functions hat.
