check-update:
  minutes: 10
  Download: true
Date: "yyyy-MM-dd"
Time: "HH:mm:ss"
Tab:
  Enable: true
  List: "%prefix%%player%%suffix% %%ping"
  Header: none
  Footer: none
Money:
  InitPlayerBalance: 500.0
  customSymbolEnabled: false
  customSymbol: ""
Banned:
  Reason: ""
  randomTempDay: false
  tempBannedDay: 7
Report_MinCount: 5
Report_MaxCount: 214748647
ScoreBoard:
  DisplayName: "%animation:Scoreboard%"
  Line:
    - "%tps%"
  interval: 1000
Location: "%world%,%x%,%y%,%z%,%yaw%,%pitch%"
Warps: "%warp% %position% (%count%),"
Warp: "%name% %position%"
Kick: "example"
